spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS, Asia/Seoul"
  level:
    root: INFO

toss:
  payments:
    secret-key: test1234
    base-url: https://api.tosspayments.com